[config]
schemaVersion = "0.0.1"

[package]
namespace = "the3venthoriz0n"
name = "MoreBees"
versionNumber = "1.0.2"
description = "It's un-bee-lievably fun!"
websiteUrl = "https://github.com/the3venthoriz0n/MoreBees"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"


[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../bin/Debug/MoreBees.dll"
target = "./MoreBees.dll"


[[build.copy]]
source = "../CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "../LICENSE"
target = "LICENSE"


[publish]
repository = "https://thunderstore.io"
communities = ["lethal-company"]

[publish.categories]
lethal-company = ["bepinex", "mods"]


