name: Publish and Release

on:
  push:
    
jobs:
  
  publish-and-release:
    name: Publish to GitHub and Thunderstore
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-artifacts
      #     path: "dist/*.zip"

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Thunderstore CLI
        run: |
          dotnet tool install -g tcli

      - name: Validate artifact exists
        run: test -d ./dist

      - name: Release on GitHub
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          make_latest: true
          files: ./dist/*.zip

      - name: Publish to Thunderstore
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.THUNDERSTORE_API_TOKEN }}
        run: |
          tcli publish --config-path ./assets/thunderstore.toml --file ./dist/*.zip 
