
name: Octo Organization CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from Octo Organization





name: Upload Thunderstore PackagePackage
description: Formats and uploads a Thunderstore package
author: AnActualEmerald
branding:
  icon: package
  color: green
inputs:
  path:
    descritpion: Path to the files of the mod. Uses the contents of the repo if not set
  community:
    description: Thunderstore community to publish to
    required: true
  namespace:
    description: Name of the team to publish the mod under
    required: true
  name:
    description: Name of the package
    required: true
  version:
    description: Package version to publish
    required: true
  icon:
    description: URL of the mod icon
  readme:
    description: URL of the mod README
  description:
    description: Description of the mod
    required: true
    default: Example mod description
  token:
    description: Thunderstore API token
    required: true
  dev:
    description: Push to thunderstore.dev rather then thunderstore.io
  wrap:
    description: Directory to wrap the contents of the repo in
  website:
    description: Homepage URL
  categories:
    description: Categories the mod belongs to
  deps:
    description: List of dependencies by name & version
  nsfw:
    description: Is the mod NSFW
  file:
    description: Prebuilt .zip file to use, relative to the repo root
  repo:
    description: The URL of the thundertore repo to publish to
outputs:
  url:
    description: URL of uploaded mod
runs:
  using: docker
  image: Dockerfile
  env:
    TCLI_AUTH_TOKEN: ${{ inputs.token }}
    TS_COMMUNITY: ${{ inputs.community }}
    TS_NAMESPACE: ${{ inputs.namespace }}
    TS_NAME: ${{ inputs.name }}
    TS_VERSION: ${{ inputs.version }}
    TS_DESC: ${{ inputs.description }}
    TS_ICON: ${{ inputs.icon }}
    TS_README: ${{ inputs.readme }}
    TS_PATH: ${{ inputs.path }}
    TS_DEV: ${{ inputs.dev }}
    TS_WRAP: ${{ inputs.wrap }}
    TS_WEBSITE: ${{ inputs.website }}
    TS_CATEGORIES: ${{ inputs.categories }}
    TS_DEPS: ${{ inputs.deps }}
    TS_NSFW: ${{ inputs.nsfw }}
    TS_FILE: ${{ inputs.file }}
    TS_REPO: ${{ inputs.repo }}


name: Upload Prebuilt Zip

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  


jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: create test zip
        run: |
          sudo apt install zip
          echo "{ \"namespace\": \"GreenTF\", \"name\": \"test\", \"description\": \"Test\", \"version_number\": \"1.${{ github.run_number }}.0\",  \"dependencies\": [], \"website_url\": \"https://greenboi.me\" }" >> manifest.json
          zip test.zip ./*
      - id: pub
        uses: ./
        with:
          namespace: GreenTF
          name: Test
          dev: true
          token: ${{ secrets.TS_KEY }}
          description: |
            The FitnessGram Pacer test is a multistage aerobic capacity test that progressively gets more difficult as it continues. 
            The 20 meter Pacer test will begin in 30 seconds. 
            Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal *boop*.
            A single lap should be completed each time you hear this sound *ding*. Remember to run in a straight line, and run as long as possible. 
            The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. 
            On your mark, get ready, start.
          version: v1.${{ github.run_number }}.0
          community: riskofrain2
          repo: thunderstore.dev
          wrap: mods
          website: "https://greenboi.me"
          categories: |
            mods
            maps
            tools
            items
          deps: |
            GreenTF-Test-0.130.0
          file: ./test.zip
      - run: echo ${{ steps.pub.outputs.url }}










# name: Publish To Thunderstore

# on:
#   release:
#     types: [published]

# jobs:
#   publish-to-thunderstore:
#     runs-on: ubuntu-latest
#     steps:
#       # Use checkout to publish the files in your repo
#       - uses: actions/checkout@main
#       - uses: GreenTF/upload-thunderstore-package@main
#         with:
#           # The thunderstore 'team' to publish under
#           namespace: the3venthoriz0n
#           description: It's un-bee-lievably fun!
#           token: ${{ secrets.API_TOKEN }}
#           name: MoreBees
#           # Use the tag as the package version
#           version: ${{ github.ref_name }}
#           community: Lethal Company
#           repo: thunderstore.io
#           categories: |
#             Mods
#             BepInEx
